### ISSUE TITLE
Action mode can sometimes not show menu options for Gallery or selection confirmation

### ISSUE THREAD

**Issue by tonyr59h** [wordpress-mobile/MediaPicker-Android#25]
A couple of reports have come in of users having no option to confirm multiple images in Action mode. For some reason the menu options don't always show up.

**Comment by sandymcfadden** [comment]
Had an app user report this and was able to duplicate. Started a new post, clicked to add images, chose Multi-select with the new picker, press and hold to start multi select, no way to add images, just an option to go back.

![screenshot_2015-07-10-06-28-16](https://cloud.githubusercontent.com/assets/1326294/8617003/ff5b8c80-26d5-11e5-9789-e61c9f0db66b.png)

Using a Nexus 5 with Android 5.1.1 and WordPress for Android 4.2.1
